apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client
  namespace: soundproud
  labels:
    stage: production
    name: client
    app: client
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        stage: production
        name: client
        app: client
    spec:
      containers:
        - name: client
          image: 'gcr.io/prisma-kube/prisma-kube-client:latest'
          ports:
            - name: client-80
              containerPort: 80
