version: '3'

services:

  client-test:
    # Should be same as client in docker-compose.yml below this point (just overwriting volumes for CI)
    build:
      # Context is this directory instead of ./client because Dockerfile
      # needs to copy schema.graphql file which is located in ./server
      context: .
      dockerfile: ./client/Dockerfile.local
    command: npm run start
    tty: true
    stdin_open: true
    ports:
      - 8080:8080

  server-test:
    # Pretty much identical to server-test in docker-compose.test.yml with
    # exception of no volumes

    # Should be same as server-test & server below this point
    ports:
      - 4001:4000
      - 4003:4003
    command:
      - /bin/sh
      - -c
      - |
        ./wait-for.sh prisma:4466
        ./node_modules/.bin/prisma deploy -e .test.env
        yarn start
    environment:
      PRISMA_ENDPOINT: http://prisma:4466/soundproud/test
    # Should be same as server below this point
    build:
      context: ./server
    depends_on:
      - prisma
    tty: true
    stdin_open: true

