version: '3'

services:

  server-test:
    # Pretty much identical to server-test in docker-compose.test.yml with
    # exception of no volumes

    # Should be same as server-test & server below this point
    ports:
      - 4001:4000
      - 4003:4003
    command:
      - /bin/sh
      - -c
      - |
        ./wait-for.sh prisma:4466
        ./node_modules/.bin/prisma deploy -e .test.env
        yarn start
    environment:
      PRISMA_ENDPOINT: http://prisma:4466/soundproud/test
    # Should be same as server below this point
    build:
      context: ./server
    depends_on:
      - prisma
    tty: true
    stdin_open: true

