version: '3'

services:
  client-test:
    image: soundproud-v3_client # use client image from docker-compose.yml
    environment:
      - API_SERVER_URL=http://localhost:4001/graphql # use server-test port
      - API_WS_SERVER_URL=ws://localhost:4001/graphql # use server-test port
    volumes:
      - ./client:/app
      - /app/node_modules
      - ./server/src/schema:/app/schema  # Need to keep schema up to date based off of server
      - /app/build
      - /app/public
      - /app/src/generated/  # Don't want to overwrite what's generated via
                             # the non-test environment.

    # Should be same as server in docker-compose.yml below this point
    command: npm run start
    tty: true
    stdin_open: true
    ports:
      - 8081:8080

  server-test:
    image: soundproud-v3_server # use server image from docker-compose.yml
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/src/generated/  # Don't want to overwrite what's generated via
                                     # the non-test environment.
    ports:
      - 4001:4000
      - 4003:4003
    command:
      - /bin/sh
      - -c
      - |
        ./wait-for.sh prisma:4466
        ./node_modules/.bin/prisma deploy -e .test.env
        yarn start
    environment:
      PRISMA_ENDPOINT: http://prisma:4466/soundproud/test
    # Should be same as server in docker-compose.yml below this point
    depends_on:
      - prisma
    tty: true
    stdin_open: true

  cypress:
    image: "cypress/included:3.4.1"
    depends_on:
      - client-test
      - server-test
    environment:
      - CYPRESS_baseUrl=http://client-test:8080
    working_dir: /e2e
    volumes:
      - ./e2e:/e2e
