version: '3'

services:
  client-test:
    image: soundproud-v3_client # use client image from docker-compose.yml
    environment:
      - API_SERVER_URL=http://server-test:8000/graphql # use server-test port
      - API_WS_SERVER_URL=ws://server-test:8000/graphql # use server-test port
    volumes:
      - ./client:/app
      - /app/node_modules
      - ./server/schema:/app/schema # Need to keep schema up to date based off of server
      - /app/build
      - /app/public
      - /app/src/generated/  # Don't want to overwrite what's generated via
                             # the non-test environment.

    # Should be same as server in docker-compose.yml below this point
    command: npm run start
    tty: true
    stdin_open: true
    ports:
      - 8081:8080

  cypress:
    image: "cypress/included:3.4.1"
    depends_on:
      - client-test
      - server
    environment:
      - CYPRESS_baseUrl=http://client-test:8080
    working_dir: /e2e
    volumes:
      - ./e2e:/e2e
