version: '3'

services:

  server-test:
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/generated/  # Don't want to overwrite what's generated via
                                 # the non-test environment.
    ports:
      - 4001:4000
      - 4003:4003
    command:
      - /bin/sh
      - -c
      - |
        ./wait-for.sh prisma:4466
        ./node_modules/.bin/prisma deploy -e .test.env
        yarn start
    environment:
      PRISMA_ENDPOINT: http://prisma:4466/soundproud/test
    # Should be same as server in docker-compose.yml below this point
    build:
      context: ./server
    depends_on:
      - prisma
    tty: true
    stdin_open: true

  cypress:
    image: "cypress/included:3.4.1"
    depends_on:
      - client
      - server
    environment:
      - CYPRESS_baseUrl=http://client:8080
    working_dir: /e2e
    volumes:
      - ./e2e:/e2e
