apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: gcr.io/prisma-kube/prisma-kube-server
    context: server
    sync:
      manual:
      - src: src/**/*
        dest: .
      - src: src/prisma.yml
        dest: ./
  - image: gcr.io/prisma-kube/prisma-kube-client
    context: client
deploy:
  kubectl:
    manifests:
    - namespace.yaml
    - database/configmap.yml
    - database/deployment.yml
    - database/pvc.yml
    - database/service.yml
    - prisma/configmap.yml
    - prisma/deployment.yaml
    - prisma/service.yml
    - server/deployment.yml
    - server/service.yml
    - client/deployment.yml
    - client/service.yml
portForward:
# - resourceType: Service
  # resourceName:	server
  # namespace: soundproud
  # port: 4000
  # localPort: 4324
- resourceType: Service
  resourceName:	prisma
  namespace: soundproud
  port: 4466
  localPort: 4467
