version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch

    steps:
      - checkout
      - setup_remote_docker
      - run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml run server-test /bin/sh -c "./wait-for.sh prisma:4466 ; npm run test"
