version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true

    steps:
      - checkout

      - run:
          name: build
          command: docker-compose -f docker-compose.yml -f docker-compose.test.yml build

      - run:
          name: server linting
          command: docker-compose -f docker-compose.yml -f docker-compose.test.yml run server-test /bin/sh -c "npm run lint"
      - run:
          name: server tests
          command: docker-compose -f docker-compose.yml -f docker-compose.test.yml run server-test /bin/sh -c "./wait-for.sh prisma:4466 ; npm run test"

      - run:
          name: client linting
          command: docker-compose -f docker-compose.yml -f docker-compose.test.yml run client npm run lint
      - run:
          name: client tests
          command: docker-compose -f docker-compose.yml -f docker-compose.test.yml run client npm run test

      - run:
          name: e2e tests
          command: docker-compose -f docker-compose.yml -f docker-compose.test.yml up --exit-code-from cypress

      - store_artifacts:
          path: e2e/cypress/videos
      - store_artifacts:
          path: e2e/cypress/screenshots
