version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: server linting
          command: docker-compose -f docker-compose.yml -f docker-compose.ci.yml run server-test /bin/sh -c "npm run lint"
      - run:
          name: server tests
          command: docker-compose -f docker-compose.yml -f docker-compose.ci.yml run server-test /bin/sh -c "./wait-for.sh prisma:4466 ; npm run test"

      - run:
          name: client linting
          command: docker-compose -f docker-compose.yml -f docker-compose.ci.yml run client-test npm run lint
      - run:
          name: client tests
          command: docker-compose -f docker-compose.yml -f docker-compose.ci.yml run client-test npm run test
