apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server
  namespace: soundproud
  labels:
    stage: production
    name: server
    app: server
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        stage: production
        name: server
        app: server
    spec:
      containers:
        - name: server
          image: 'gcr.io/prisma-kube/prisma-kube-server:latest'
          ports:
            - name: server-4000
              containerPort: 4000
      imagePullSecrets:
        - name: regcred
