apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: database
  namespace: soundproud
  labels:
    stage: production
    name: database
    app: postgresql
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        stage: production
        name: database
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: 'postgres:10.4'
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: database-disk
          ports:
            - name: postgresql-5432
              containerPort: 5432
      volumes:
        - name: database-disk
          persistentVolumeClaim:
            claimName: database-disk
