kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database-disk
  namespace: soundproud
  labels:
    stage: production
    name: database
    app: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
