apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: soundproud
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    stage: production
    name: database
    app: postgresql
